Problem_link : https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [1]:
import numpy as np

In [5]:
n, m = map(int, input().split())

1 4


In [11]:
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)

1 2 3
2 3 4


In [17]:
#print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')
# or 
print(*[eval('a'+i+'b') for i in ['+','-','*','//','%','**']], sep='\n')

[[3 7 9]]
[[-1 -3 -3]]
[[ 2 10 18]]
[[0 0 0]]
[[1 2 3]]
[[  1  32 729]]
