problem_link: https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [1]:
import numpy as np

In [5]:
n = int(input())

2


In [7]:
a = np.array([input().split() for _ in range(n)], int)
print(a)
b = np.array([input().split() for _ in range(n)], int)
print(b)

1 2 
3 4 
[[1 2]
 [3 4]]
1 2 
3 4
[[1 2]
 [3 4]]


In [9]:
print(np.dot(a,b))

[[ 7 10]
 [15 22]]
