problem_link: https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [2]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

1 2 3
1 2 3
14
[[1 2 3]
 [2 4 6]
 [3 6 9]]
