In [1]:
#problem
#https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [8]:
import numpy as np

In [ ]:
arr =np.array([int(x) for x in input().split()])
reshap = arr.reshape(3,3)
print(reshap)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
