In [1]:
import numpy as np


In [6]:
n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)

2 2
1 2
2 3


In [7]:
print(array)

[[1 2]
 [2 3]]


In [8]:
print(np.transpose(array))
print(array.flatten())

[[1 2]
 [2 3]]
[1 2 2 3]
