## Identity Matrix
An identity array is a square matrix with all the main diagonal elements as  and the rest as 0.

In [1]:
import numpy as np


In [5]:
identity_mat = np.identity(3,dtype=int)        #for 3*3 square matrix
print(identity_mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## eye 
The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

In [24]:
eye_mat = np.eye(4,4,k=4)
print(eye_mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
