## Mathmetical operations on matrix


In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4,])
print(A)
B = np.array([5,6,7,8])
print(B)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(A+B) #addition
#or
np.add(A,B)

[ 6  8 10 12]


array([ 6,  8, 10, 12])

In [11]:
print(A-B) #asubtraction
np.subtract(A,B)

[-4 -4 -4 -4]


array([-4, -4, -4, -4])

In [12]:
np.multiply(A,B)

array([ 5, 12, 21, 32])

In [13]:
np.divide(A,B)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [16]:
np.mod(A,B)
print(A%B)

[1 2 3 4]


In [17]:
np.power(A,B)

array([    1,    64,  2187, 65536])