## Transpose
The row become column and column become row.
We can generate the transposition of an array using the tool numpy.transpose. 
It will not affect the original array, but it will create a new array.

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
print(np.transpose(arr))

[[1 4]
 [2 5]
 [3 6]]


## Flatten
The tool flatten creates a copy of the input array flattened to one dimension.


In [11]:
print(arr.flatten())

[1 2 3 4 5 6]
